source(file.path(dirname(sub('^--file=','',grep('^--file=',commandArgs(),value=TRUE)[1])),'00_config.R'))
start_log('01_inspect_singlecell')
suppressPackageStartupMessages({library(qs);library(SeuratObject);library(Matrix)})
sc <- qread(SC_INPUT)
cat('sc dim',dim(sc),'\n');print(colnames(sc@meta.data));print(class(sc[['RNA']]));print(slotNames(sc[['RNA']]))
md <- sc@meta.data
print(table(md$orig.ident))
for(n in intersect(c('fresh_frozen','sample_type','technology','final_label','tissue'),names(md))) {cat(n,'\n');print(table(md[[n]],useNA='ifany'))}
ct <- GetAssayData(sc,assay='RNA',layer='counts');dt <- GetAssayData(sc,assay='RNA',layer='data')
stopifnot(identical(dimnames(ct),dimnames(dt)),identical(colnames(ct),rownames(md)))
diag <- data.frame(sample=md$orig.ident,count_sum=Matrix::colSums(ct),data_sum=Matrix::colSums(dt),count_features=Matrix::colSums(ct>0),data_features=Matrix::colSums(dt>0))
summ <- do.call(rbind,lapply(split(diag,diag$sample),function(d)data.frame(sample=d$sample[1],n=nrow(d),median_count=median(d$count_sum),median_data=median(d$data_sum),median_count_features=median(d$count_features),median_data_features=median(d$data_features),zero_data=sum(d$data_sum==0))))
print(summ);write_result(summ,'singlecell_input_diagnostics')
cat('Counts integer check',max(abs(head(ct@x,1000000)-round(head(ct@x,1000000)))),'\n')
cat('Data nonzero quantiles\n');print(quantile(dt@x,c(0,.25,.5,.75,1)))
set.seed(20260906);ii<-sample(ncol(ct),min(300,ncol(ct)))
z<-ct[,ii,drop=FALSE]%*%Diagonal(x=10000/Matrix::colSums(ct[,ii,drop=FALSE]));z@x<-log1p(z@x)
err<-Matrix::colSums(abs(z-dt[,ii,drop=FALSE]))
print(aggregate(as.numeric(err),list(sample=md$orig.ident[ii]),median))
saveRDS(md,file.path(OUT,'singlecell_input_metadata.rds'))
end_log()
